//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.27 at 02:31:14 AM BRT 
//


package br.com.globo.entidades;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "channel"
})
@XmlRootElement(name = "rss")
public class Rss {

    @XmlElement(required = true)
    protected Rss.Channel channel;
    @XmlAttribute
    protected BigDecimal version;

    public Rss.Channel getChannel() {
        return channel;
    }

    public void setChannel(Rss.Channel value) {
        this.channel = value;
    }

    public BigDecimal getVersion() {
        return version;
    }

    public void setVersion(BigDecimal value) {
        this.version = value;
    }
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "link",
        "description",
        "language",
        "copyright",
        "image",
        "item"
    })
    public static class Channel {

        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String link;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected String language;
        @XmlElement(required = true)
        protected String copyright;
        @XmlElement(required = true)
        protected Rss.Channel.Image image;
        @XmlElement(required = true)
        protected List<Rss.Channel.Item> item;

        public String getTitle() {
            return title;
        }
        public void setTitle(String value) {
            this.title = value;
        }
        public String getLink() {
            return link;
        }
        public void setLink(String value) {
            this.link = value;
        }
        public String getDescription() {
            return description;
        }

        public void setDescription(String value) {
            this.description = value;
        }

        public String getLanguage() {
            return language;
        }

        public void setLanguage(String value) {
            this.language = value;
        }

        public String getCopyright() {
            return copyright;
        }
        public void setCopyright(String value) {
            this.copyright = value;
        }

        public Rss.Channel.Image getImage() {
            return image;
        }

        public void setImage(Rss.Channel.Image value) {
            this.image = value;
        }
        public List<Rss.Channel.Item> getItem() {
            if (item == null) {
                item = new ArrayList<Rss.Channel.Item>();
            }
            return this.item;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "url",
            "title",
            "link"
        })
        public static class Image {

            @XmlElement(required = true)
            protected String url;
            @XmlElement(required = true)
            protected String title;
            @XmlElement(required = true)
            protected String link;

            public String getUrl() {
                return url;
            }
            public void setUrl(String value) {
                this.url = value;
            }
            public String getTitle() {
                return title;
            }

            public void setTitle(String value) {
                this.title = value;
            }
            public String getLink() {
                return link;
            }

            public void setLink(String value) {
                this.link = value;
            }

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "title",
            "description",
            "link",
            "dcCreator",
            "guid"
        })
        public static class Item {

            @XmlElement(required = true)
            protected String title;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(required = true)
            protected String link;
            @XmlElement(name = "dc_creator", required = true)
            protected String dcCreator;
            protected int guid;

            public String getTitle() {
                return title;
            }

            public void setTitle(String value) {
                this.title = value;
            }
            public String getDescription() {
                return description;
            }
            public void setDescription(String value) {
                this.description = value;
            }
            public String getLink() {
                return link;
            }
            public void setLink(String value) {
                this.link = value;
            }
            public String getDcCreator() {
                return dcCreator;
            }
            public void setDcCreator(String value) {
                this.dcCreator = value;
            }
            public int getGuid() {
                return guid;
            }
            public void setGuid(int value) {
                this.guid = value;
            }

        }

    }

}
